### ISSUE TITLE
Update documentation on pypi

### ISSUE THREAD

**Issue by mpibpc-mroose** [charettes/django-testdata#10]
When reading the documentation on [pypi](https://pypi.org/project/django-testdata/) I found a small typo in the second and third example:

```
from testdata import testdata  # should be wrap_testdata

...

class BookTests(TestCase):
    @classmethod
    @wrap_testdata  # will not work according to the actual import
```

The import should be `from testdata import wrap_testdata` as it already is on Github's readme.

So the documentations diverge on both platform which should be avoided. I'm pretty unsire wher this could come from as the `setup.py` looks fine. So I guess it's only a small thing which is going wrong.

**Comment by charettes** [comment]
Should be fixed now https://pypi.org/project/django-testdata/

Thanks for the report.
